set(GLFW_TARGET glfw)
set(GLFW_URL https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.zip)

include(FetchContent)
FetchContent_Declare(${GLFW_TARGET} URL ${GLFW_URL})
FetchContent_GetProperties(${GLFW_TARGET})
if(NOT glfw_POPULATED)
  FetchContent_Populate(${GLFW_TARGET})
  SET(GLFW_BUILD_DOCS OFF CACHE BOOL "Build the GLFW documentation")
  SET(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "Build the GLFW example programs")
  SET(GLFW_BUILD_TESTS OFF CACHE BOOL "Build the GLFW test programs")
  SET(GLFW_INSTALL OFF CACHE BOOL "Generate installation target")
  add_subdirectory(${glfw_SOURCE_DIR} ${glfw_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()